Repository Inteli-College/2025-1A-T12-EC05-G05, pull requests merged in 2025-04, with the labels that each got.

#78 docs: monitoramento qr code
  docs/docs/robo/hardwares_periféricos.md
  docs/static/img/qr_code_scanner.jpeg
Labels: documentation

#81 Feat/popup fitas
  src/backend/app/instance/db.sqlite
  src/backend/app/services/statusfitas_service.py
  src/frontend/src/components/PopUpFitas.jsx
  src/frontend/src/components/Table.jsx
  src/frontend/src/pages/AFazer.jsx
  src/frontend/src/pages/EmProgresso.jsx
  src/frontend/src/pages/Prontas.jsx
  src/frontend/src/pages/fitaMedicamentos.jsx
Labels: code

#69 style: adiciona pagination nas tabelas
  src/frontend/src/pages/AFazer.jsx
  src/frontend/src/pages/Devolvidas.jsx
  src/frontend/src/pages/EmProgresso.jsx
  src/frontend/src/pages/PossivelDevolucao.jsx
  src/frontend/src/pages/Prontas.jsx
Labels: style

#92 feat: adiciona rota de sensores bem como sua lógica
  src/backend/app/__init__.py
  src/backend/app/controllers/qrcode_controller.py
  src/backend/app/controllers/robot_controller.py
  src/backend/app/controllers/sensores_controller.py
  src/backend/app/services/sensors_service.py
Labels: code

#93 feat: tela inventario
  src/frontend/src/assets/icones/addbin-icon.svg
  src/frontend/src/components/AddBin.jsx
  src/frontend/src/components/Bin.jsx
  src/frontend/src/pages/inventario.jsx
  src/frontend/src/styles/AddBin.css
  src/frontend/src/styles/Bin.css
  src/frontend/src/styles/Inventario.css
Labels: code

#94 feat: adiciona rota de logs
  src/backend/app/controllers/logs_controller.py
  src/backend/app/models.py
  src/backend/app/services/logs_service.py
Labels: code

#97 Feat/logs tela login
  src/backend/app/controllers/logs_controller.py
  src/backend/app/models.py
  src/backend/app/services/logs_service.py
  src/frontend/src/components/SideBar.jsx
  src/frontend/src/components/Table.jsx
  src/frontend/src/pages/Logs.jsx
  src/frontend/src/pages/historico.jsx
  src/frontend/src/pages/login.jsx
Labels: code

#98 Fix/ajusta bug pop up tela fitas
  src/backend/app/models.py
  src/backend/app/services/statusfitas_service.py
  src/frontend/src/components/PopUpFitas.jsx
Labels: bug

#96 Docs/arquitetura
  docs/docs/arquitetura_solucao/diagrama_detalhado_blocos.md
  docs/static/img/diagrama_de_blocos.png
Labels: documentation

#110 docs: atualização do front e do prototipo de alta
  docs/docs/interfaces/prototipo_alta_fidelidade.md
  docs/static/img/altafid_homepage.png
  docs/static/img/altafid_popup_coleta_unitaria.png
Labels: documentation
