Repository Inteli-College/2025-1A-T12-EC05-G05, pull requests merged in 2025-03, with the labels that each got.

#25 Feat/cria esteira ci
  .github/pull_request_template.md
  .github/workflows/ci.yml
Labels: code

#23 Feat/cria auto deploy docs
  .github/workflows/deploy.yml
  docs/docs/arquitetura_solucao/diagrama_blocos.md
  docs/docs/canvas_proposta_valor.md
  docs/docs/entendimento_do_suário/Elisabeth.md
  docs/docs/entendimento_do_suário/Márcio.md
  docs/docusaurus.config.js
Labels: code

#29 Docs/como rodar a aplicação e cli
  docs/docs/Inicialização.md
  docs/docusaurus.config.js
  src/.gitignore
  src/README.md
  src/dobot/requirements.txt
Labels: documentation

#34 Style/estiliza tela de login
  src/frontend/src/assets/fundo.svg
  src/frontend/src/assets/icones/cadeado.svg
  src/frontend/src/assets/icones/usuario.svg
  src/frontend/src/assets/logo-claro.svg
  src/frontend/src/assets/logo-pequeno.svg
  src/frontend/src/components/header.jsx
  src/frontend/src/pages/login.jsx
  src/frontend/src/styles/header.css
  src/frontend/src/styles/login.css
Labels: style

#42 Feat/adiciona codigo do rasp e nova rota
  requirements.txt
  src/backend/app/app.py
  src/backend/app/cli.log
  src/backend/instance/dbCli.sqlite
  src/dobot/cli.log
  src/dobot/cli_debug.log
  src/dobot/cli_pfr.py
  src/dobot/controller/sensores.py
  src/dobot/instance/dbCli.sqlite
  src/frontend/src/assets/fundo.svg
  src/frontend/src/assets/icones/cadeado.svg
  src/frontend/src/assets/icones/usuario.svg
  src/frontend/src/assets/logo-claro.svg
  src/frontend/src/assets/logo-pequeno.svg
  src/frontend/src/components/header.jsx
  src/frontend/src/pages/login.jsx
  src/frontend/src/styles/header.css
  src/frontend/src/styles/login.css
  src/instance/dbCli.sqlite
Labels: code

#38 Feat/adiciona componente de side bar e estiliza tela not found
  .github/pull_request_template.md
  .github/workflows/ci.yml
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/Layout.jsx
  src/frontend/src/Router.jsx
  src/frontend/src/assets/icones/agenda.svg
  src/frontend/src/assets/icones/calendario.svg
  src/frontend/src/assets/icones/lupa.svg
  src/frontend/src/assets/icones/sair.svg
  src/frontend/src/assets/icones/seta-voltar.svg
  src/frontend/src/assets/icones/seta.svg
  src/frontend/src/assets/notFound.svg
  src/frontend/src/assets/pilula.svg
  src/frontend/src/assets/seringa.svg
  src/frontend/src/components/.gitkeep
  src/frontend/src/components/PageHeader.jsx
  src/frontend/src/components/SideBar.jsx
  src/frontend/src/components/Table.jsx
  src/frontend/src/pages/AFazer.jsx
  src/frontend/src/pages/EmProgresso.jsx
  src/frontend/src/pages/Prontas.jsx
  src/frontend/src/pages/fitaMedicamentos.jsx
  src/frontend/src/pages/historico.jsx
  src/frontend/src/pages/notFound.jsx
  src/frontend/src/styles/Historico.css
  src/frontend/src/styles/Layout.css
  src/frontend/src/styles/NotFound.css
  src/frontend/src/styles/PageHeader.css
  src/frontend/src/styles/SideBar.css
  src/frontend/src/styles/Table.css
  src/frontend/src/styles/fitaMedicamentos.css
Labels: code, style

#45 Feat/cli para controle do dobot e perifericos
  requirements.txt
  src/backend/app/app.py
  src/backend/app/cli.log
  src/backend/instance/dbCli.sqlite
  src/dobot/cli.log
  src/dobot/cli_debug.log
  src/dobot/cli_pfr.py
  src/dobot/controller/sensores.py
  src/dobot/dbCli.sqlite
  src/dobot/instance/dbCli.sqlite
  src/instance/dbCli.sqlite
Labels: code

#43 Docs/diagrama blocos
  .gitignore
  docs/docs/arquitetura_solucao/diagrama_blocos.md
  docs/docs/arquitetura_solucao/diagrama_detalhado_blocos.md
  docs/static/img/arquiteraDetalhadaBlocos.jpeg
Labels: documentation

#44 docs: Adiciona documentação do robô e dos hardwares periféricos
  docs/docs/robo/hardwares_periféricos.md
  docs/docs/robo/index.md
  package-lock.json
  package.json
Labels: documentation

#53 feat: adiciona função de logout
  src/frontend/src/components/SideBar.jsx
  src/frontend/src/pages/Logs.jsx
Labels: code

#58 Feat/paginafitas
  src/backend/app/controllers/statusfitas_controller.py
  src/backend/app/instance/db.sqlite
  src/backend/app/instance/popula_banco.py
  src/backend/app/models.py
  src/backend/app/services/statusfitas_service.py
  src/frontend/src/pages/AFazer.jsx
  src/frontend/src/pages/EmProgresso.jsx
  src/frontend/src/pages/Prontas.jsx
  src/frontend/src/pages/fitaMedicamentos.jsx
Labels: code

#54 docs: atualizacao jornada
  docs/docs/entendimento_do_suário/Elisabeth.md
  docs/docs/entendimento_do_suário/Márcio.md
  docs/static/img/jornada-usuario-marcio-atualizada.png
Labels: documentation
